---
# mysql配置
mysql:
  host: '127.0.0.1'
  db: 'mhsb_gt_kel'
  username: 'Ubuntu'
  password: '123456'
  port: 3306
  createSql: ""     # 数据库初始化创建表
  modifySql: ""  # 修改表结构
  procedureSql: ""  # 存储过程sql
# mongo配置
mongo:
  host: '127.0.0.1'
  port: 8051
  db: 'mhsb_kel'
  username: 'kel'
  password: '123456'
# 生产服务器IP, 用于更新DDNS服务， VPN服务器
gpus: [0]

version: 0
compModel:
  detmodel: kcomp
  detepoch: 617
#  detmodel: comp
#  detepoch: 925

partModel:
#  detmodel: part
#  detepoch: 83
  detmodel: kpart
  detepoch: 617

#version: 1
#compNormal:
#  detmodel: detcomp
#  detepoch: 415
#
#rfcnpart:
#  detmodel: detpart
#  detepoch: 415

# 日志配置
#  CRITICAL = 50
#  FATAL = CRITICAL
#  ERROR = 40
#  WARNING = 30
#  WARN = WARNING
#  INFO = 20
#  DEBUG = 10
#  NOTSET = 0
logger:
  logger_level: 10      # Log等级总开关
  clogger_level: 10      # 输出到控制台等级
  flogger_level: 10     # 输出到日志文件中的等级
  #  logPath: ""     # 日志文件的路径, 在log下
  # logFormat: "%(asctime)s-%(levelname)s-%(name)s: %(message)s"      # 日志的输出格式
  # logFormat: "%(message)s"      # 日志的输出格式
  isConsole: True      # 是否输出到控制台
  isLogInFile: True      # 是否输出到日志文件中
  isIndERROR: False    # 是否将error信息独立输出到单独文件

camera: #数据格式为 相机位号, 旋转角度
#@params1: 旋转机位的相机id
#@params2: 0:顺时针旋转90度  1:顺时针旋转180度  2:顺时针270度
#@params3: 未旋转前的图片宽度, @params4: 未旋转前的图片高度
#  - !!python/tuple [16, 2, 4920, 3280]
#  - !!python/tuple [19, 2, 4920, 3280]
bugtypeControl:
  isIgnSusp: true # 忽略疑似缺陷总开关
  ignoreUncertains:   # 忽略的疑似缺陷字典　　　key(构件名称): !!python/list [value(子零件名称),...]
    C_DX_YW:
#    C_DWZZ: !!python/list ["P_LS_QS","P_LS_BMSD"]

ignoreCache: true
# recognize the pole-number imges or not
isreco_pole: true

# Restful
restful:
  port: 80

# DNS配置
dns:
  id: ''
  secret: ''

# 保存杆号图片的磁盘文件夹
poleImgDir: '/disk_workspace/poleImg'